[package]
name = "d05-rejection"
version = "0.1.0"
authors = ["xue35@Mac <xue35@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
