[package]
name = "a06_tls"
version = "0.1.0"
authors = ["rpi400 <xue35@icloud.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-rustls = { version = "0.22", optional = true }
warp = { version ="0.3", features = ["tls"] }

